export interface IMusicState {
  // banner 轮播图
  banners: any[]
  recommendPlaylist: any[]
  privateContentList: any[]
  rcmdNewPlaylsit: any[]
  rcmdMVlist: any[]
  hotTags: any[]
  highqualityTags: any[]
  hotPlaylist: any[]
  highqualityPlaylist: any[]
  allPrivateContentList: any[]
  toplist: any[]
  superList: any[]
  cloudList: any[]
  globalList: any[]
  patternList: any[]
  artistsList: any[]
  newSongsList: any[]
}
